/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAttackChainRouteImport } from './routes/_authenticated/attack-chain'
import { Route as AuthenticatedPatchesRouteImport } from './routes/_authenticated/patches'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated/scans'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedThreatsRouteImport } from './routes/_authenticated/threats'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks.$taskId'
import { Route as AuthenticatedToolsBlueRouteImport } from './routes/_authenticated/tools.blue'
import { Route as AuthenticatedToolsRedRouteImport } from './routes/_authenticated/tools.red'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttackChainRoute =
  AuthenticatedAttackChainRouteImport.update({
    id: '/attack-chain',
    path: '/attack-chain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatchesRoute = AuthenticatedPatchesRouteImport.update({
  id: '/patches',
  path: '/patches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThreatsRoute = AuthenticatedThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedToolsBlueRoute = AuthenticatedToolsBlueRouteImport.update({
  id: '/tools/blue',
  path: '/tools/blue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRedRoute = AuthenticatedToolsRedRouteImport.update({
  id: '/tools/red',
  path: '/tools/red',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attack-chain': typeof AuthenticatedAttackChainRoute
  '/patches': typeof AuthenticatedPatchesRoute
  '/scans': typeof AuthenticatedScansRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/threats': typeof AuthenticatedThreatsRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tools/blue': typeof AuthenticatedToolsBlueRoute
  '/tools/red': typeof AuthenticatedToolsRedRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attack-chain': typeof AuthenticatedAttackChainRoute
  '/patches': typeof AuthenticatedPatchesRoute
  '/scans': typeof AuthenticatedScansRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/threats': typeof AuthenticatedThreatsRoute
  '/': typeof AuthenticatedIndexRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tools/blue': typeof AuthenticatedToolsBlueRoute
  '/tools/red': typeof AuthenticatedToolsRedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/attack-chain': typeof AuthenticatedAttackChainRoute
  '/_authenticated/patches': typeof AuthenticatedPatchesRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/threats': typeof AuthenticatedThreatsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tools/blue': typeof AuthenticatedToolsBlueRoute
  '/_authenticated/tools/red': typeof AuthenticatedToolsRedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/attack-chain'
    | '/patches'
    | '/scans'
    | '/tasks'
    | '/threats'
    | '/tasks/$taskId'
    | '/tools/blue'
    | '/tools/red'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/attack-chain'
    | '/patches'
    | '/scans'
    | '/tasks'
    | '/threats'
    | '/'
    | '/tasks/$taskId'
    | '/tools/blue'
    | '/tools/red'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/attack-chain'
    | '/_authenticated/patches'
    | '/_authenticated/scans'
    | '/_authenticated/tasks'
    | '/_authenticated/threats'
    | '/_authenticated/'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tools/blue'
    | '/_authenticated/tools/red'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attack-chain': {
      id: '/_authenticated/attack-chain'
      path: '/attack-chain'
      fullPath: '/attack-chain'
      preLoaderRoute: typeof AuthenticatedAttackChainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patches': {
      id: '/_authenticated/patches'
      path: '/patches'
      fullPath: '/patches'
      preLoaderRoute: typeof AuthenticatedPatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/threats': {
      id: '/_authenticated/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof AuthenticatedThreatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tools/blue': {
      id: '/_authenticated/tools/blue'
      path: '/tools/blue'
      fullPath: '/tools/blue'
      preLoaderRoute: typeof AuthenticatedToolsBlueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/red': {
      id: '/_authenticated/tools/red'
      path: '/tools/red'
      fullPath: '/tools/red'
      preLoaderRoute: typeof AuthenticatedToolsRedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAttackChainRoute: typeof AuthenticatedAttackChainRoute
  AuthenticatedPatchesRoute: typeof AuthenticatedPatchesRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedThreatsRoute: typeof AuthenticatedThreatsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedToolsBlueRoute: typeof AuthenticatedToolsBlueRoute
  AuthenticatedToolsRedRoute: typeof AuthenticatedToolsRedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAttackChainRoute: AuthenticatedAttackChainRoute,
  AuthenticatedPatchesRoute: AuthenticatedPatchesRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedThreatsRoute: AuthenticatedThreatsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedToolsBlueRoute: AuthenticatedToolsBlueRoute,
  AuthenticatedToolsRedRoute: AuthenticatedToolsRedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
